### ISSUE TITLE
Hoe to take the argument from command-line?

### ISSUE THREAD

**Issue by siavash13** [cbarrick/gulp-run#24]
I need to take an argument from the command line and use it in the gulp-file ?
This is my `gulpfile.js` 
      var run = require('gulp-run');
 
       gulp.task('default', function () {
         run('echo Hello user').exec() 
          .pipe(gulp.dest('output'))    
       })
How can I take an argument from Command line and pass it to this file , so that `hello argument1` is pprinted instead of `hello user`?

**Comment by cbarrick** [comment]
I believe your question may be outside of the scope of this project. But something like this might work:

```javascript
gulp.task('default', function () {
     run('echo Hello ' + process.argv[1]).exec() 
      .pipe(gulp.dest('output'))    
   })
```
