### ISSUE TITLE
maxBuffer isn't handled properly

### ISSUE THREAD

**Issue by phazei** [cbarrick/gulp-run#32]
Found an issue that kept coming up after server was running a few hours.  Server has a heartbeat that outputs to stdout every 5 seconds.  After a few hours the buffer fills up.  Once that happens, the child process crashes.  There are two issue with here.

First, when the server crashes, somewhere it's being caught and there's no message or anything.  The server just stops, still running.  The child process was the only thing left, so it should all die.  There's no way to see the error.  It took days to discover what was stopping.

Second, there's no setting to increase the maxBuffer.  The default size is 200 * 1024 which is really small and there are many long running processes that might need something more customizable.

**Comment by cbarrick** [comment]
See #33

**Comment by phazei** [comment]
I need to look into this issue further, probably this weekend.
There's absolutely a bug somewhere in it.
The issue doesn't exist when I'm not using gulp-run, so I believe it's somewhere in here, but since spawn is being used, maxBuffer shouldn't be the issue.  I did find it doesn't crash with exec and a large maxBuffer, OTOH, spawn seems more flexible.  I'd suggest reverting #33. Sorry about that.

**Comment by phazei** [comment]
Here is a test case:

```javascript
var
    childProcess = require('child_process'),
    gulp = require('gulp'),
    run = require('gulp-run');

gulp.task('test', function(done){
    var cmd = "gulp test-long";

    //This hangs rather quickly (usually at i=49
    run(cmd,{
        verbosity:3
    }).exec();

    //This never dies
    /*
    var subshell = childProcess.spawn('sh', [
        '-c', cmd
    ], {env: process.env});
    subshell.stdout.pipe(process.stdout);
    subshell.stderr.pipe(process.stderr);
    subshell.stderr.pipe(process.stderr);
    subshell.once('close', function (code) {
        //this is never called
        console.log('PROCESS PROPERLY ENDED');
    });
    //*/
});

gulp.task('test-long', function(done){
    var i = 0;
    setInterval(function() {
        //The longer this is, the sooner it dies.
        console.log("LOTS OF STUFF: " + i++);
        console.log("--------------------------------------------------------------------------------------------------------------------------------");
        console.log("--------------------------------------------------------------------------------------------------------------------------------");
        console.log("--------------------------------------------------------------------------------------------------------------------------------");
        console.log("--------------------------------------------------------------------------------------------------------------------------------");
        console.log("--------------------------------------------------------------------------------------------------------------------------------");
    }, 100);
});

```
